export const kitsData = [
  {
    "title": "Groove ",
    "highlightText": "Shield",
    "subtitle":
      "Easy integration of sensors, actuators, and inputs for rapid IoT prototyping",
    "bannerPoints": [
      "Plug-and-play modular system for rapid prototyping",
      "Standardized Grove 4-pin interface for sensors and modules",
      "Compatible with BLE development kits and Arduino ecosystem",
    ],
    "features": [
      "Plug-and-play modular system for quick sensor and module integration",
      "Standardized Grove interface with 4-pin connectors.",
      "Compatible with BLE development kits for simplified prototyping",
      "No soldering required, enabling faster project development",
      "Scalable design supporting multiple Grove modules simultaneously",
    ],
    "applications": [
      "Rapid Prototyping – Quickly test sensors, actuators, and wireless modules",
      "IoT Development – Connect BLE-enabled boards with Grove sensors",
      "Wearables & Health Monitoring – Integrate bio-sensors with BLE kits",
      "STEM Education & Learning – Teaching electronics and IoT concepts",
      "Smart Systems – Build scalable automation and monitoring solutions",
    ],
    "specifications": [
      "Operating Voltage: 3.3 V / 5 V (depends on development kit)",
      "Interfaces: Digital, Analog, I²C, UART via Grove connectors",
      "Connector Type: Standard 4-pin Grove headers",
      "Compatibility: Works with Arduino, BLE kits, and Seeed Studio Grove ecosystem",
      "Form Factor: Shield/hat design for easy stacking on development boards",
      "Prototyping Support: Simplifies modular prototyping without soldering",
      "Design: Compact and scalable for multiple module connections",
      "Use Case: Ideal for rapid IoT prototyping and educational projects",
    ],
    "imagePath": "assets/images/groove.png",
    "pdfPath": "assets/pdfs/GROOVE.pdf",
    "email": "Vikash.hardwareengineer@ihub-awadh.in",
    "datasheetKey": "GROOVE",
  },
  {
    "title": "Arduino Based ",
    "highlightText": "Robotic Kit",
    "subtitle":
      "Versatile Arduino Nano-based kit with motor drivers, Bluetooth, and sensor interfaces",
    "bannerPoints": [
      "Built-in Arduino Nano (ATmega328P) with L293D motor driver",
      "Supports multiple communication interfaces: Bluetooth, I²C, and UART",
      "Integrated OLED display and sensor sockets for rapid prototyping",
    ],
    "features": [
      "Pre-integrated Arduino Nano with L293D motor driver for DC/stepper motors",
      "Dedicated sockets for Bluetooth, OLED, and MQ-series sensors",
      "Onboard buzzer and protection circuitry for reliable operation",
      "Multiple GPIO and expansion headers for sensors, servos, and add-on modules",
    ],
    "applications": [
      "Bluetooth-controlled robotic cars and smart vehicles",
      "IoT-based environmental and automation projects",
      "Educational robotics and embedded system training",
      "Prototyping of mobile robots, alert systems, and automation devices",
    ],
    "specifications": [
      "Microcontroller: ATmega328P (Arduino Nano compatible)",
      "Operating Voltage: 5V DC; Input: 7–12V DC (Barrel/USB-C)",
      "Motor Driver: L293D Dual H-Bridge, 2 channels (DC/stepper), 4.5–36V, 600mA per channel",
      "Communication Interfaces: HC-05 Bluetooth, I²C, UART, SPI (optional)",
      "Display: 0.96″ OLED (I²C interface)",
      "Supported Sensors: MQ-series gas, ultrasonic, potentiometer",
      "Power Supply: 5V regulated, DC barrel jack, USB-C, onboard regulator",
      "Protection: Reverse-polarity (SS34 diode) and overcurrent protection",
    ],
    "imagePath": "assets/images/robotickitrender.png",
    "pdfPath": "assets/pdfs/ARDUINO.pdf",
    "email": "Vikash.hardwareengineer@ihub-awadh.in",
    "datasheetKey": "ArduinoRoboticKit",
  },
  {
    "title": "nRF52832-Based ",
    "highlightText": "Robotic Kit",
    "subtitle":
      "High-performance Bluetooth 5.0 robotic kit with motor drivers, OLED display, and sensor support",
    "bannerPoints": [
      "Powered by ARM Cortex-M4F MCU (nRF52832) with Bluetooth 5.0",
      "Integrated L293D motor driver for smooth motor control",
      "Supports OLED display and multiple sensor interfaces",
    ],
    "features": [
      "High-performance ARM Cortex-M4F processor for fast and smooth robot control",
      "Bluetooth 5.0 connectivity for reliable real-time IoT communication",
      "Onboard OLED interface for live data visualization and feedback",
      "Expandable sensor support for gas, ultrasonic, and analog sensors",
      "Modular design with USB-C power and multiple I/O & PWM expansion pins",
      "Ideal for learning, prototyping, and smart robotics development",
    ],
    "applications": [
      "Smart robotic projects such as line followers and obstacle-avoiding robots",
      "IoT and mobile robots integrating wireless sensors and control systems",
      "STEM learning platform for embedded systems and programming education",
      "Sensor-based experiments for gas detection and environmental monitoring",
      "Prototyping and innovation in smart automation systems",
      "Educational competitions and lab-based robotics workshops",
    ],
    "specifications": [
      "Microcontroller: Nordic nRF52832 (ARM Cortex-M4F, 64 MHz, 512 KB Flash, 64 KB SRAM)",
      "Wireless Connectivity: Integrated BLE 5.0 for reliable communication",
      "Motor Driver: L293D Dual H-Bridge, 2 DC motors or 1 stepper, 4.5–36V, 600mA/channel",
      "Display: 0.96″ OLED (I²C interface) for live data and feedback",
      "Sensors: MQ gas sensor header, ultrasonic interface, potentiometer calibration",
      "Power: USB Type-C and 7–12V DC input with onboard 3.3V/5V regulators",
      "Expansion: Multiple GPIO, PWM, and ADC pins for motors and peripherals",
      "Extras: Onboard buzzer, reset button, and LEDs for real-time feedback",
    ],
    "imagePath": "assets/images/nrf52832_robotickit.png",
    "pdfPath": "assets/pdfs/nRFrobotic.pdf",
    "email": "Vikash.hardwareengineer@ihub-awadh.in",
    "datasheetKey": "nRF52832RoboticKit",
  },
  {
    "title": "Bluetooth Low Energy",
    "highlightText": "Development Kit",
    "subtitle":
      "Multi-protocol wireless prototyping kit for IoT and smart devices",
    "bannerPoints": [
      "Supports Bluetooth Low Energy, Mesh, ANT, and 2.4 GHz",
      "Arduino Uno Rev. 3 compatible for prototyping",
      "Includes on-board SEGGER J-Link debugger",
    ],
    "features": [
      "Rapid prototyping board tailored for IoT and wireless applications",
      "Multi-protocol support: Bluetooth LE, Bluetooth Mesh, ANT, proprietary 2.4 GHz",
      "Enhanced Bluetooth 5 capability with higher throughput and extended advertising",
      "User-friendly design with 4 programmable buttons and 4 LEDs",
      "Plug-and-play compatibility with Arduino Uno Rev. 3 shields",
      "On-board SEGGER J-Link debugger for seamless development",
      "External SoC programming and debugging via dedicated header",
      "Integrated antenna for stable wireless performance",
      "Flexible powering options: USB, external supply, or CR2032 battery",
      "Compatible with IDEs like SEGGER Embedded Studio, Visual Studio, Keil, GCC, and IAR",
    ],
    "applications": [
      "IoT Devices – Smart home hubs, connected sensors, automation controllers",
      "Wearables – Fitness trackers, health monitors, smartwatches",
      "Smart Lighting – Professional and consumer-grade wireless lighting systems",
      "Industrial Monitoring – Asset tracking, predictive maintenance, sensor logging",
      "Environmental Monitoring – Air quality, weather stations, smart agriculture",
      "Wireless Audio – LE Audio prototypes and Bluetooth-based sound systems",
      "Healthcare Devices – Medical wearables and patient monitoring solutions",
      "Automotive Applications – Vehicle diagnostics, tracking, infotainment",
      "Educational Development – Training kits, student projects, prototyping platforms",
      "Smart Infrastructure – Building automation and energy management systems",
    ],
    "specifications": [
      "Processor: Arm Cortex-M4F @ 64 MHz with FPU and DSP instructions",
      "Memory: 512 kB Flash, 64 kB RAM (on-chip)",
      "Connectivity: Bluetooth 5, ANT, 2.4 GHz proprietary",
      "Interfaces: GPIO, UART, SPI, I²C, ADC, PWM routed to edge connectors",
      "Debugging Interface: SEGGER J-Link OB with SWD support",
      "Power Supply Voltage: 1.7 V – 3.3 V (USB, external supply, CR2032 battery)",
      "Antenna: 2.4 GHz PCB trace antenna",
      "Form Factor: Arduino Uno Rev. 3 layout (~68 mm × 52 mm)",
      "User I/O: 4 LEDs and 4 push-buttons",
      "Operating Conditions: -40°C to +85°C (industrial grade)",
    ],
    "imagePath": "assets/images/ble_dev_kit.jpg",
    "pdfPath": "assets/pdfs/BLEKIT.pdf",
    "email": "Vikash.hardwareengineer@ihub-awadh.in",
    "datasheetKey": "BLEKIT",
    "nreCodeLink":
      "https://github.com/sksuman14/nRF_All_Sensors_Codes/tree/main/Blink_Led/Led_Blink",
    "nrfUICodeLink":
      "https://github.com/sksuman14/Cps_Lab_All_nRF_UI_Code/tree/main/Led_Blink_UI",
  }
];
